import { describe, expect, it } from 'vitest'
import { applySubstitutionEvidence } from './apply-substitution-evidence.mjs'
const dataset = { items: { '1': { id: 1, nameKo: '기본' }, '2': { id: 2, nameKo: '고급' }, '3': { id: 3, nameKo: '결과' } }, recipes: { 'cooking:3': { id: 'cooking:3', skill: 'cooking', outputItemId: 3, yield: { min: 1, max: 1 }, variants: [{ id: 'v1', inputs: [{ itemId: 1, count: 5 }] }] } }, recipesByOutput: { '3': ['cooking:3'] }, metadata: { sources: ['client'] } }
const evidence = { source: 'BDO Codex KR', collectedAt: '2026-09-23T00:00:00.000Z', groups: [{ id: 'codex:3001', sourceId: '3001', sourceUrl: 'https://bdocodex.com/kr/materialgroup/3001/', members: [{ itemId: 1, value: 1 }, { itemId: 2, value: 6 }] }] }
describe('applySubstitutionEvidence', () => {
  it('installs source-backed membership/Worth and binds matching canonical recipe inputs', () => { const result = applySubstitutionEvidence(dataset, evidence); expect(result.substitutionGroups['codex:3001'].memberItemIds).toEqual([1, 2]); expect(result.substitutionGroups['codex:3001'].memberValueByItemId).toEqual({ '1': 1, '2': 6 }); expect(result.recipes['cooking:3'].variants[0].inputs[0].substitutionGroupId).toBe('codex:3001'); expect(dataset.recipes['cooking:3'].variants[0].inputs[0].substitutionGroupId).toBeUndefined() })
  it('replaces the prior Codex snapshot instead of retaining stale groups/bindings', () => { const stale = structuredClone(dataset); stale.substitutionGroups = { 'codex:9999': { id: 'codex:9999', memberItemIds: [1, 2], memberValueByItemId: { '1': 1, '2': 2 }, source: { provider: 'BDO Codex KR', sourceId: '9999', sourceUrl: 'https://bdocodex.com/kr/materialgroup/9999/', verifiedAt: '2026-01-01T00:00:00Z' } } }; stale.recipes['cooking:3'].variants[0].inputs[0].substitutionGroupId = 'codex:9999'; const result = applySubstitutionEvidence(stale, evidence); expect(result.substitutionGroups['codex:9999']).toBeUndefined(); expect(result.recipes['cooking:3'].variants[0].inputs[0].substitutionGroupId).toBe('codex:3001') })
  it('preserves singleton source groups without inventing substitution semantics', () => { const singleton = { id: 'codex:6026', sourceId: '6026', sourceUrl: 'https://bdocodex.com/kr/materialgroup/6026/', members: [{ itemId: 1, value: 1 }] }; const result = applySubstitutionEvidence(dataset, { ...evidence, groups: [singleton] }); expect(result.substitutionGroups['codex:6026'].memberItemIds).toEqual([1]); expect(result.recipes['cooking:3'].variants[0].inputs[0].substitutionGroupId).toBeUndefined() })
  it('rejects partial or non-positive Worth evidence', () => { expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [{ ...evidence.groups[0], members: [{ itemId: 1, value: 0 }, { itemId: 2, value: 6 }] }] })).toThrow(/invalid Worth/) })
  it('rejects evidence members absent from canonical items', () => { expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [{ ...evidence.groups[0], members: [{ itemId: 1, value: 1 }, { itemId: 99, value: 6 }] }] })).toThrow(/unknown\/invalid member/) })
  it('requires canonical id, sourceId, and KR Codex URL to agree', () => { expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [{ ...evidence.groups[0], sourceUrl: 'https://example.com/group/3001' }] })).toThrow(/evidence URL does not match sourceId/); expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [{ ...evidence.groups[0], sourceId: '3002' }] })).toThrow(/sourceId does not match canonical group id/) })
  it('rejects duplicate group records', () => { expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [evidence.groups[0], { ...evidence.groups[0] }] })).toThrow(/duplicate group evidence/) })
  it('fails closed when one ingredient belongs to multiple sourced groups', () => { const second = { id: 'codex:9999', sourceId: '9999', sourceUrl: 'https://bdocodex.com/kr/materialgroup/9999/', members: [{ itemId: 1, value: 1 }, { itemId: 2, value: 2 }] }; expect(() => applySubstitutionEvidence(dataset, { ...evidence, groups: [evidence.groups[0], second] })).toThrow(/multiple sourced substitution groups/) })
})
